accerciser                 \
                               alsa-utils                 \
                               ansible-base               \
                               ansible-lint               \
                               appstream-glib             \
                               autoconf-archive           \
                               caja-rename                \
                               configurator-git           \
                               docker-compose             \
                               fbu                        \
                               flatpak                    \
                               flatpak-builder            \
                               glib2-docs                 \
                               gnome-builder              \
                               gnome-code-assistance      \
                               gnome-common               \
                               gnome-music                \
                               gobject-introspection      \
                               grub2-theme-preview        \
                               gtk-doc                    \
                               gtksourceview3             \
                               inkcut                     \
                               intltool                   \
                               ipython                    \
                               itstool                    \
                               jsonrpc-glib               \
                               libgit2-glib               \
                               libvirt-python             \
                               mallard-ducktype           \
                               mate-common                \
                               meson                      \
                               ninja                      \
                               obhud                      \
                               optipng                    \
                               ostree                     \
                               pacman-utils               \
                               pacman-utils-data          \
                               parallel                   \
                               pkg-audit                  \
                               py3status-git              \
                               python-aenum               \
                               python-anytree             \
                               python-apipkg              \
                               python-astroid             \
                               python-atom                \
                               python-automat             \
                               python-babel               \
                               python-backcall            \
                               python-bcrypt              \
                               python-beaker              \
                               python-bracex              \
                               python-bytecode-git        \
                               python-cached-property     \
                               python-chardet             \
                               python-click-completion    \
                               python-cmp_version         \
                               python-commonmark          \
                               python-constantly          \
                               python-coverage            \
                               python-decorator           \
                               python-distro              \
                               python-docker              \
                               python-docker-pycreds      \
                               python-dockerpty           \
                               python-docutils            \
                               python-dotenv              \
                               python-enaml               \
                               python-enamlx              \
                               python-enrich              \
                               python-execnet             \
                               python-func_timeout        \
                               python-gtts                \
                               python-gtts-token          \
                               python-hyperlink           \
                               python-idna                \
                               python-imagesize           \
                               python-incremental         \
                               python-iniconfig           \
                               python-ipykernel           \
                               python-isort               \
                               python-jinja               \
                               python-jsonpickle          \
                               python-jsonschema          \
                               python-jupyter_client      \
                               python-jupyter_core        \
                               python-kiwisolver          \
                               python-lazy-object-proxy   \
                               python-linux-procfs        \
                               python-mako                \
                               python-markupsafe          \
                               python-mccabe              \
                               python-mock                \
                               python-more-itertools      \
                               python-numpy               \
                               python-ordered-set         \
                               python-packaging           \
                               python-pandas              \
                               python-paramiko            \
                               python-path                \
                               python-pbr                 \
                               python-perf                \
                               python-pexpect             \
                               python-pickleshare         \
                               python-pluggy              \
                               python-pmw                 \
                               python-prompt_toolkit      \
                               python-psutil              \
                               python-ptyprocess          \
                               python-py                  \
                               python-pyaml               \
                               python-pycodestyle         \
                               python-pycups              \
                               python-pyfiglet            \
                               python-pyflakes            \
                               python-pygments            \
                               python-pyinotify           \
                               python-pylint              \
                               python-pynacl              \
                               python-pyqtgraph           \
                               python-pyrsistent          \
                               python-pyserial            \
                               python-pystache            \
                               python-pytest              \
                               python-pytest-cov          \
                               python-pytest-fixture-config \
                               python-pytest-shutil         \
                               python-pytest-virtualenv     \
                               python-pytz                  \
                               python-pyudev                \
                               python-pyzmq                 \
                               python-qt-reactor            \
                               python-qtconsole             \
                               python-qtpy                  \
                               python-requests              \
                               python-rich                  \
                               python-ruamel-yaml           \
                               python-ruamel.yaml.clib      \
                               python-schedutils            \
                               python-setuptools            \
                               python-setuptools-scm        \
                               python-shellingham           \
                               python-simplejson            \
                               python-snowballstemmer       \
                               python-sphinx                \
                               python-sphinx-alabaster-theme          \
                               python-sphinxcontrib-applehelp         \
                               python-sphinxcontrib-devhelp           \
                               python-sphinxcontrib-htmlhelp          \
                               python-sphinxcontrib-jsmath            \
                               python-sphinxcontrib-qthelp            \
                               python-sphinxcontrib-serializinghtml   \
                               python-tenacity                        \
                               python-texttable                       \
                               python-toml                            \
                               python-tornado                         \
                               python-traitlets                       \
                               python-twisted                         \
                               python-typing_extensions               \
                               python-wcmatch                         \
                               python-websocket-client                \
                               python-wheel                           \
                               python-wrapt                           \
                               python-zope-interface                  \
                               qtile                                  \
                               rpmextract                             \
                               ruby-dbus                              \
                               sgtk-menu                              \
                               template-glib                          \
                               themix-export-spotify-git              \
                               themix-full-git                        \
                               themix-gui-git                         \
                               themix-icons-archdroid-git             \
                               themix-icons-gnome-colors-git          \
                               themix-icons-numix-git                 \
                               themix-icons-papirus-git               \
                               themix-icons-suru-plus-aspromauros-git \
                               themix-icons-suru-plus-git             \
                               themix-import-images-git               \
                               themix-plugin-base16-git               \
                               themix-theme-materia-git               \
                               themix-theme-oomox-git                 \
                               thinkpad-scripts                       \
                               tuned                                  \
                               vala                                   \
                               virt-install                           \
                               virt-manager                           \
                               wget                                   \
                               xautomation                            \
                               xdg-desktop-portal                     \
                               xdg-desktop-portal-gtk                 \
                               xf86-input-synaptics                   \
                               yelp-tools                             \
                               python-pyparsing                       \


